DROP TABLE IF EXISTS reservations;

CREATE TABLE reservations (
  id SERIAL PRIMARY KEY,
  restaurant_id INT DEFAULT NULL,
  name VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  date DATE DEFAULT NULL,
  time VARCHAR(10) DEFAULT NULL,
  remark VARCHAR(1000) DEFAULT NULL,
  number_of_people INT DEFAULT NULL
);

DROP TABLE IF EXISTS restaurants;

CREATE TABLE restaurants (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) DEFAULT NULL,
  city VARCHAR(100) DEFAULT NULL,
  image VARCHAR(100) DEFAULT NULL,
  stars INT DEFAULT NULL
);

INSERT INTO restaurants (id, name, city, image, stars) VALUES
  (1, 'Zilte', 'Antwerpen', 'zilte.jpg', 3),
  (2, 'Hof van Cleve', 'Kruishoutem', 'hofvancleve.jpg', 3),
	(3,'Bon bon','Sint-Pieters-Woluwe','bonbon.jpg',2),
	(4,'Le Chalet de la Forêt','Ukkel','restaurant.jpg',2),
	(5,'Comme Chez Soi','Brussel','Comme_chez_Soi.jpg',2),
	(6,'La Paix','Anderlecht','Lepaix.jpg',2),
	(7,'The Jane','Antwerpen','thejane.jpg',2),
	(8,'Castor','Beveren-Leie','restaurant.jpg',2),
	(9,'Nuance','Duffel','restaurant.jpg',2),
	(10,'Hostellerie St-Nicolas','Elverdinge','restaurant.jpg',2),
	(11,'Vrijmoed','Gent','restaurant.jpg',2),
	(12,'La Durée','Izegem','restaurant.jpg',2),
	(13,'Bartholomeus','Knokke-Heist','restaurant.jpg',2),
	(14,'Cuchara','Lommel','restaurant.jpg',2),
	(15,'La Source','Neerharen','restaurant.jpg',2),
	(16,'Slagmolen','Opglabbeek','restaurant.jpg',2),
	(17,'Hostellerie Le Fox','De Panne','restaurant.jpg',2),
	(18,'Pastorale','Reet','restaurant.jpg',2),
	(19,'Boury','Roeselare','restaurant.jpg',3),
	(20,'De Jonkman','Sint-Kruis','restaurant.jpg',2),
	(21,'Bozar Restaurant','Brussel','restaurant.jpg',2),
	(22,'La Canne en Ville','Elsene','restaurant.jpg',2),
	(23,'Da Mimmo','Sint-Lambrechts-Woluwe','restaurant.jpg',2),
	(24,'Kamo','Elsene','restaurant.jpg',2),
	(25,'Le Pigeon Noir','Ukkel','restaurant.jpg',2),
	(26,'San Daniele','Ganshoren','restaurant.jpg',2),
	(27,'senzanome','Brussel','restaurant.jpg',2),
	(28,'La Truffe Noire','Brussel','restaurant.jpg',2),
	(29,'La Villa Emily','Brussel','restaurant.jpg',2),
	(30,'La Villa in the sky','Elsene','restaurant.jpg',2),
	(31,'Wine in the City','Jette','restaurant.jpg',2),
	(32,'Kelderman','Aalst','restaurant.jpg',1),
	(33,'''t Overhamme','Aalst','restaurant.jpg',1),
	(34,'Bistrot du Nord','Antwerpen','restaurant.jpg',1),
	(35,'The Butcher''s son','Antwerpen','restaurant.jpg',1),
	(36,'Dôme','Antwerpen','restaurant.jpg',1),
	(37,'t Fornuis','Antwerpen','restaurant.jpg',1),
	(38,'FRANQ','Antwerpen','restaurant.jpg',1),
	(39,'Het Gebaar','Antwerpen','restaurant.jpg',1),
	(40,'Kommilfoo','Antwerpen','restaurant.jpg',1),
	(41,'Nathan','Antwerpen','restaurant.jpg',1),
	(42,'Le Pristine','Antwerpen','restaurant.jpg',1),
	(43,'Colette - De Vijvers','Averbode','restaurant.jpg',1),
	(44,'Hofke van Bazel','Bazel','restaurant.jpg',1),
	(45,'Eyckerhof','Bornem','restaurant.jpg',1),
	(46,'Den Gouden Harynck','Brugge','restaurant.jpg',1),
	(47,'L.E.S.S.','Brugge','restaurant.jpg',1),
	(48,'Sans Cravate','Brugge','restaurant.jpg',1),
	(49,'ZetJoe by Geert Van Hecke','Brugge','restaurant.jpg',1),
	(50,'De Zuidkant','Damme','restaurant.jpg',1),
	(51,'Marcus','Deerlijk','restaurant.jpg',1),
	(52,'''t Truffeltje','Dendermonde','restaurant.jpg',1),
	(53,'Hostellerie Vivendum','Dilsen','restaurant.jpg',1),
	(54,'Libertine','Erpe','restaurant.jpg',1),
	(55,'La Belle','Geel','restaurant.jpg',1),
	(56,'De Kristalijn','Genk','restaurant.jpg',1),
	(57,'Horseele','Gent','restaurant.jpg',1),
	(58,'OAK','Gent','restaurant.jpg',1),
	(59,'Publiek','Gent','restaurant.jpg',1),
	(60,'Souvenir','Gent','restaurant.jpg',1),
	(61,'dEssensi','''s-Gravenwezel','restaurant.jpg',1),
	(62,'Michel','Groot-Bijgaarden','restaurant.jpg',1),
	(63,'JER','Hasselt','restaurant.jpg',1),
	(64,'Ogst','Hasselt','restaurant.jpg',1),
	(65,'De Vork van Luc Bellings','Hasselt','restaurant.jpg',1),
	(66,'Arenberg','Heverlee','restaurant.jpg',1),
	(67,'Couvert couvert','Heverlee','restaurant.jpg',1),
	(68,'Innesto','Houthalen','restaurant.jpg',1),
	(69,'Hof Ter Hulst','Hulshout','restaurant.jpg',1),
	(70,'Boo Raan','Knokke-Heist','restaurant.jpg',1),
	(71,'Cuines,33','Knokke-Heist','restaurant.jpg',1),
	(72,'Sel Gris','Knokke-Heist','restaurant.jpg',1),
	(73,'Willem Hiele','Koksijde','restaurant.jpg',1),
	(74,'EED','Leuven','restaurant.jpg',1),
	(75,'EssenCiel','Leuven','restaurant.jpg',1),
	(76,'De Pastorie','Lichtaart','restaurant.jpg',1),
	(77,'Vol-Ver','Marke','restaurant.jpg',1),
	(78,'''t Korennaer','Nieuwkerken-Waas','restaurant.jpg',1),
	(79,'M-Bistro','Nieuwpoort','restaurant.jpg',1),
	(80,'Benoit en Bernard Dewitte','Ouwegem','restaurant.jpg',1),
	(81,'Alain Bianchin','Overijse','restaurant.jpg',1),
	(82,'Auberge de Herborist','Sint-Andries','restaurant.jpg',1),
	(83,'LEnvie','Sint-Denijs','restaurant.jpg',1),
	(84,'Carcasse','Sint-Idesbald','restaurant.jpg',1),
	(85,'Centpourcent','Sint-Katelijne-Waver','restaurant.jpg',1),
	(86,'Goffin','Sint-Kruis','restaurant.jpg',1),
	(87,'Sir Kwinten','Sint-Kwintens-Lennik','restaurant.jpg',1),
	(88,'Brasserie Julie','Sint-Martens-Bodegem','restaurant.jpg',1),
	(89,'Bar Bulot','Sint-Michiels','restaurant.jpg',1),
	(90,'t Stoveke','Strombeek-Bever','restaurant.jpg',1),
	(91,'Melchior','Tienen','restaurant.jpg',1),
	(92,'Altermezzo','Tongeren','restaurant.jpg',1),
	(93,'Magis','Tongeren','restaurant.jpg',1),
	(94,'De Mijlpaal','Tongeren','restaurant.jpg',1);
